### ISSUE TITLE
how to set h1 header as chapter in latex output?

### ISSUE THREAD

**Issue by 0x0f0f0f** [MichaelHatherly/Publish.jl#22]

**Comment by MichaelHatherly** [comment]
`h1` is fixed to `section` at the moment in `CommonMark.jl`. You can use a raw latex block to add chapters:

````markdown
```{=latex}
\chapter{Title}
```
````

We could consider whether having a way to "shift" header levels is worth doing, but it might be more complexity than worth it for something that can be set using a `{=latex}` block like above.

**Comment by 0x0f0f0f** [comment]
Im doing this already. Thanks! Shifting header levels should is a quite complex feature to implement in CommonMark.jl
