### ISSUE TITLE
`deploy` creates recursive copies of every version under the current build folder

### ISSUE THREAD

**Issue by darsnack** [MichaelHatherly/Publish.jl#44]
See https://github.com/darsnack/ParameterSchedulers.jl/runs/5008548052?check_suite_focus=true and https://github.com/darsnack/ParameterSchedulers.jl/tree/gh-pages.

Each version folder contains a subfolder called `gh-pages` that contains every prior version. Why does this happen? I don't see the same thing happening for Publish.jl's documentation.

**Comment by MichaelHatherly** [comment]
https://github.com/MichaelHatherly/Publish.jl/blob/master/Project.toml#L49 is the secret to ignoring them.

**Comment by darsnack** [comment]
Awesome, thanks!
