### ISSUE TITLE
Using an HTML template

### ISSUE THREAD

**Issue by darsnack** [MichaelHatherly/Publish.jl#5]
Can HTML templates be used without specifying a custom theme? I have `publish.html.template.file` pointing to a `docs/custom.mustache`, but none of the changes appear reflected in the live server. Custom CSS files appear to be working by setting `publish.html.css`.

**Comment by MichaelHatherly** [comment]
It *should* work like that, but looks like it's probably a bug in the config override order.

```diff
diff --git a/src/themes.jl b/src/themes.jl
index 4f64ead..620e0d8 100644
--- a/src/themes.jl
+++ b/src/themes.jl
@@ -45,7 +45,7 @@ function loadtheme(tree::FileTree, env::AbstractDict)
         isfile(file) || error("'$theme' theme does not exist.")
     end
     dict = TOML.parsefile(string(file))
-    env = rmerge(env, Dict("publish" => dict))
+    env = rmerge(Dict("publish" => dict), env)
     tree′ = FileTree(dirname(file))
     tree′ = FileTrees.load(tree′; lazy=LAZY[]) do file
         loadfile(env, joinpath(basename(tree′), path(file)))
```

If you're able to confirm the above diff fixes it that would be great.

**Comment by darsnack** [comment]
Yes, that worked! Thank you.
